version: '3'

vars:
  BUILD_OUT_DIR: './build'
  BUILD_APP_NAME: 'scruffy'
  BUILD_EXTENSION: '{{if eq OS "windows"}}.exe{{end}}'
  GIT_TAG_VERSION:
    sh: git describe --tags --abbrev=0 --match "v*"
  GIT_COMMIT:
    # git log -n 1 --format=%h
    sh: git rev-parse --short HEAD
  GIT_DIRTY: 
    sh: |
      if [ -n "$(git status --porcelain)" ]; then
        echo " (dirty index)"
      fi
  GIT_STATUS: "commit {{.GIT_COMMIT}}{{.GIT_DIRTY}}"
  BUILD_LDFLAGS: '-s -w -X "mateusjdev/scruffy/cmd.ApplicationVersion={{.GIT_TAG_VERSION}} - {{.GIT_STATUS}}"'

tasks:
  internal-build:
    internal: true
    requires:
      vars: [BUILD_OUTPUT]
    env:
      GOOS: "{{.GOOS | default OS}}"
      GOARCH: "{{.GOARCH | default ARCH}}"
    cmd: go build -o {{ .BUILD_OUTPUT }}{{.BUILD_EXTENSION}} -ldflags='{{ .BUILD_LDFLAGS }}'

  internal-build-os-arch:
    internal: true
    requires:
      vars: [GOOS, GOARCH]
    cmds:
      - task: internal-build
        vars:
          BUILD_OUTPUT: "{{ .BUILD_OUT_DIR }}/{{ .BUILD_APP_NAME }}-{{.GOOS}}-{{.GOARCH}}"
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"

  build-linux-arm64:
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "linux"
          GOARCH: "arm64"

  build-linux-amd64:
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "linux"
          GOARCH: "amd64"

  build-windows-amd64:
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "windows"
          GOARCH: "amd64"

  build-all:
    cmds:
      - task: build-linux-arm64
      - task: build-linux-amd64
      - task: build-windows-amd64

  build:
    vars:
      BUILD_OUTPUT: "{{ .BUILD_OUT_DIR }}/{{ .BUILD_APP_NAME }}"
    cmds:
      - task: internal-build
        vars:
          BUILD_OUTPUT: "{{.BUILD_OUTPUT}}"

  install:
    cmds:
      - go install -ldflags='{{ .BUILD_LDFLAGS }}'
